### PR TITLE
Run notebooks for updated fragment library

### PR DESCRIPTION
**Pull request by dominiquesydow**
## Description

1. Run all notebooks with updated fragment library and check connectivity-related parts for changes (none really expected since only 12 fragments were changed).
2. Add notebook for reduced fragment library generation.

## Todos

- [x] Update `util.py`: 
  - [x] Make `read_fragment_library` more versatile (load ROMol from SDF with/without dummy atoms; in 2d/3D; add SMILES with/without dummy atoms) 
  - [x] Rename drug-like and fragment-like functions with ro5 and ro3!
- [x] Rerun `quick_start.ipynb` (refactor code where tasks can be done more easily)
- [x] Remove `fragment_library.ipynb` (extended `read_fragment_library()` makes need for a csv file obsolete because the function already processes all the information created in this notebook)
- [x] Rerun `original_ligands.ipynb` (no changes)
- [x] Rerun `fragment_analysis.ipynb` (changes in connectivity-part)
- [x] Refactor and rerun `cluster_most_common_fragments.ipynb` (refactor code)
    - @AndreaVolkamer's comment: Add cluster statistics (cluster ID vs. size plot) > `plot_cluster_sizes()`
    - Entangle main function: 
      - `get_clustered_most_common_fragments()`: Create DataFrame for fragment counts (with SMILES, ROMol) and add cluster IDs (refactor `util.py` functions)
      - `draw_clusters`: Draw most common fragments sorted by cluster and fragment count
    - Refactor top X common fragments: Include also fragments that make not the top X cutoff but have the same fragment count as the fragment on rank X.
- [x] Add `fragment_analysis_literature.ipynb` (move Yang et al. comparison here and extend in the future with all already conducted comparisons which were done off-line)
- [x] Add `fragment_library_reduced.ipynb`: Select diverse subset of fragments for recombination; save as sdf files (per subpocket with X-ray structure atom coordinates) and csv file (all subpockets)

## Questions

- [x] 1. Add more clarity to singleton vs. duplicates / deduplication terminology?
    - Restructured *8. Fragment promiscuity*, added term definitions to *Singletons vs. fragments with duplicates in subpocket pool* section
- [x] 2. 'Ligands with multiple fragments per subpocket' - not fully clear what's meant (we had calculated above 'Number of fragments that have connections into the same subpocket multiple times: 74') does this belong together?  
  - Yes, it does, I merged the analysis of both questions in section "5. Fragments occurrences per subpocket" > "Ligands with multiple fragments per subpocket": 
    - 1. How many ligands have fragments occupying the same subpocket multiple times? (126)
    - 2. How many ligands have fragments occupying the same subpocket and thereby connecting to the same neighbor subpocket? (74)
    - (Ligands from question 2 are a subset of ligands from question 1.)
- [x] 3. in `n_fragments_per_subpocket_per_ligand.reset_index().groupby(['subpocket', 'n_fragments']).size()` does the result mean there is a ligand in which FP is visited 3-times? if so, I would be interested to see which one this is ...
  - Yes, correct, I added the ligand + its fragmentation to section "5. Fragments occurrences per subpocket" > "Ligands with multiple fragments per subpocket"
- [x] 4. in '7. Fragment similarity per subpockets': just wondering if the full matrix is calculated or only half (i.e. sim(A,B)=sim(B,A))
    - Half the matrix: Each combination is only calculated once using `itertools.combinations`: 
`util.get_fragment_similarity_per_subpocket()`

## Status

- [ ] Ready to go

### CODE REVIEW

**Comment by AndreaVolkamer** [comment]
@dominiquesydow nicely structured PR!!!
Quick question: When running the quick_start notebook, it fails to import klifs_utils in utils.py (used in get_original_ligands)? How does one need to link this?

**Comment by AndreaVolkamer** [comment]
@dominiquesydow thanks for your help, just adding this here so we don't forget to add the line:
!pip install git+https://github.com/volkamerlab/klifs_utils.git@lib-skeleton

**Comment by AndreaVolkamer** [comment]
Pushed my edits on fragment_analysis.ipynb. Great notebook, @dominiquesydow !!!

Small things we could discuss offline:
- I got confused by the 'singleton' percentage (first touched in step 5 (where I almost added `(stats_n_fragments['freq_singletons']= 100 - stats_n_fragments.freq_duplicates)`), then later in 'Singleton fragments (in promiscuity) talk about this point'
- We could think about (in the very end) adding the respective figure captions from the manuscript here also (cam to my mind when checking Figure 3B, its hard to guess where the numbers above the bars come from)
- 'Ligands with multiple fragments per subpocket' - not fully clear whats meant (we had calculated above 'Number of fragments that have connections into the same subpocket multiple times: 74') does this belong together?
- in `n_fragments_per_subpocket_per_ligand.reset_index().groupby(['subpocket', 'n_fragments']).size()` does the result mean there is a ligand in which FP is visited 3-times? if so, i would be interested to see which one this is ...
- in '7. Fragment similarity per subpockets': just wondering if the full matrix is calculated or only half (i.e. sim(A,B)=sim(B,A))
- 'Some more details on the descriptor values per subpocket' not sure where this line belongs to?
- Miscellaneous: Yang et al. publication add DOI/link; and what is the result of the analysis (we should have found it?)

**Comment by dominiquesydow** [comment]
> * I got confused by the 'singleton' percentage (first touched in step 5 (where I almost added `(stats_n_fragments['freq_singletons']= 100 - stats_n_fragments.freq_duplicates)`), then later in 'Singleton fragments (in promiscuity)'
> 
> * We could think about (in the very end) adding the respective figure captions from the manuscript here also (came to my mind when checking Figure 3B, it's hard to guess where the numbers above the bars come from)
> 
> * 'Ligands with multiple fragments per subpocket' - not fully clear what's meant (we had calculated above 'Number of fragments that have connections into the same subpocket multiple times: 74') does this belong together?
> 
> * in `n_fragments_per_subpocket_per_ligand.reset_index().groupby(['subpocket', 'n_fragments']).size()` does the result mean there is a ligand in which FP is visited 3-times? if so, I would be interested to see which one this is ...
> 
> * in '7. Fragment similarity per subpockets': just wondering if the full matrix is calculated or only half (i.e. sim(A,B)=sim(B,A))
> 
> * 'Some more details on the descriptor values per subpocket' not sure where this line belongs to?
> 
> * Miscellaneous: Yang et al. publication add DOI/link; and what is the result of the analysis (we should have found it?)

Thank a lot for this thorough review, @AndreaVolkamer! And thanks for adding the substructure highlights, that's super helpful!
I will your comments/questions to the "Questions" section of the PR, so that I can track my work on them better.

**Comment by dominiquesydow** [comment]
> I got confused by the 'singleton' percentage (first touched in step 5 (where I almost added `(stats_n_fragments['freq_singletons']= 100 - stats_n_fragments.freq_duplicates)`), then later in 'Singleton fragments (in promiscuity)'

That is a good point. 

I thought of **duplicate molecules** as molecules that are copies of a molecule in the library. Example: If we had 3 benzenes in the library, we would have 1 "original" benzene and 2 duplicates/copies of benzene. In the deduplication step, we remove these 2 copies to retain only the "original" benzene. 

**Singleton molecules** are molecules that occur only once in the library, so there are no copies.

When we calculate `100 - stats_n_fragments.freq_duplicates`, I think we calculate the percentage of molecules in the library that remain after deduplication, i.e. both **singleton molecules** and the **"original" molecule of duplicate molecules**. 

Thus, to me it would be more:
`stats_n_fragments['freq_deduplicated_fragments']= 100 - stats_n_fragments.freq_duplicates`

Let me know what you think. The deduplication definition is a reoccurring source of unclarity, so we might consider renaming (copy instead of duplicates; xxx instead of deduplication).

**Comment by dominiquesydow** [comment]
> in '7. Fragment similarity per subpockets': just wondering if the full matrix is calculated or only half (i.e. sim(A,B)=sim(B,A))

Half the matrix: Each combination is only calculated once using `itertools.combinations`: 
`util.get_fragment_similarity_per_subpocket()`

**Comment by dominiquesydow** [comment]
> We could think about (in the very end) adding the respective figure captions from the manuscript here also (came to my mind when checking Figure 3B, it's hard to guess where the numbers above the bars come from)

Moved to issue #10; to be worked when manuscript figures final.

**Comment by dominiquesydow** [comment]
> 'Some more details on the descriptor values per subpocket' not sure where this line belongs to?

That is odd - using Jupyter lab I cannot the the cells either, but using Jupyter notebook and the GitHub view does show them. No clue. I have seen the same for the cluster_most_common_fragments.ipynb. Will get back to this.

**Comment by AndreaVolkamer** [comment]
Sorry, @dominiquesydow: I meant to have pushed the last thing this afternoon already. 
Minor comment: Should we add numbers in which order the notebooks should be used? 1_xxx.ipynb
(just found that the KLIFS_utils installation info is in original_ligands.ipynb and I reviewed the nbs in different order)

**Comment by dominiquesydow** [comment]
Thanks, @AndreaVolkamer! 

> Minor comment: Should we add numbers in which order the notebooks should be used? 1_xxx.ipynb
(just found that the KLIFS_utils installation info is in original_ligands.ipynb and I reviewed the nbs in different order)

Yes to renaming, I had that on my list, too - this needs a new PR after this one (since I am not sure if we can see diffs anymore if the filename changed).

**Comment by dominiquesydow** [comment]
This is a note to myself regarding Question 4:

I think both calculations (4. "Connections per fragment" and 5. "Ligands with multiple fragments per subpocket") should yield the same result but yield 74 and 126, respectively.

Steps to do tomorrow:

- Move content in 4. "Connections per fragment" to 5.
- In 4. "Connections per fragment": `get_connections_by_fragment` seems not to be used for anything - check if I can delete this.
- Compare `get_connections_by_ligand` in 4. with calculation in 5. to find out why the results differ.
- When all this is fixed, answer Question 3.

**Comment by dominiquesydow** [comment]
@AndreaVolkamer: I am coming back to you regarding two questions of yours regarding this notebook:
https://github.com/volkamerlab/KinFragLib/blob/notebooks_with_new_data/notebooks/fragment_analysis.ipynb

>  2. 'Ligands with multiple fragments per subpocket' - not fully clear what's meant (we had calculated above 'Number of fragments that have connections into the same subpocket multiple times: 74') does this belong together?

Contrary to the quick assessment in my previous post, we look here at different situations:

1. How many ligands have fragments occupying the same subpocket multiple times? (126)
2. How many ligands have fragments occupying the same subpocket and thereby connecting to the same neighbor subpocket? (74)
(Ligands from question 2 are a subset of ligands from question 1.)

I merged the analysis of both questions in section "5. Fragments occurrences per subpocket" > "Ligands with multiple fragments per subpocket".

> 3. in n_fragments_per_subpocket_per_ligand.reset_index().groupby(['subpocket', 'n_fragments']).size() does the result mean there is a ligand in which FP is visited 3-times? if so, I would be interested to see which one this is ...

Yes, correct, I added the ligand + its fragmentation to the same section. Two small fragments where split from the large and unfragmentable AP fragment. I think it is still ok.
image
https://klifs.vu-compmedchem.nl/details.php?structure_id=4957

**Comment by dominiquesydow** [comment]
@AndreaVolkamer - I think we are ready to merge this PR. 

Next steps can be done in a new PR (this one is already very, very complex, my apologies).

**Comment by AndreaVolkamer** [comment]
@dominiquesydow thanks for the detailed explanations on the above questions.
- tiny comment on the last (3*FP), I also think its ok. Ideally the last FP would be assigned to SE or X, but that's not a bug, and kinda a consequence of our design choices.

**Comment by dominiquesydow** [comment]
Merging back to `master`! :)

**Pull request merged**
